name: log artifact

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: log_artifact
steps:
    - uses: actions/checkout@v2
    - run: sh executeForLogs.sh
    - uses: actions/upload-artifact@v2
      with:
        name: log_artifact
        path: ./log.log
